Repository masang1/majang.frontend, pull requests merged in 2023-07, with the labels that each got.

#6 feat(component): add header
  src/App.tsx
  src/components/common/Button/index.tsx
  src/components/index.ts
  src/components/main/Header/index.tsx
  src/components/main/Header/styled.ts
  src/components/main/index.ts
  src/screens/main/index.tsx
  src/styles/colors.ts
  src/styles/component.ts
  src/styles/index.ts
Labels: 🎨 디자인

#8 feat: add bottom tab & fix screen
  package-lock.json
  package.json
  src/App.tsx
  src/screens/chat/index.tsx
  src/screens/home/index.tsx
  src/screens/index.ts
  src/screens/main/index.tsx
  src/screens/my/index.tsx
  src/screens/registration/index.tsx
  src/screens/search/index.tsx
Labels: ✨ 기능, 🎨 디자인

#14 refactor: changed App.tsx location
  App.tsx
Labels: ♻️ 리팩토링

#18 fix: button height, font bug
  App.tsx
  src/components/common/Button/index.tsx
  src/components/common/Button/styled.ts
  src/components/common/Text/styled.ts
  src/screens/auth/main/index.tsx
Labels: 🎨 디자인, 🐛 버그

#27 feature: add legal footer
  App.tsx
  src/components/home/Footer/index.tsx
  src/components/home/Footer/styled.ts
  src/components/home/Header/index.tsx
  src/components/home/Header/styled.ts
  src/components/home/index.ts
  src/components/index.ts
  src/constant/footer.ts
  src/constant/index.ts
  src/hooks/useCheckNumber.ts
  src/screens/home/index.tsx
  src/screens/home/styled.ts
  src/styles/component.ts
  src/styles/index.ts
Labels: ✨ 기능, 🎨 디자인

#29 feat: add user authentication
  App.tsx
  src/Router.tsx
  src/api/api.tsx
  src/api/auth.ts
  src/components/home/Header/styled.ts
  src/hooks/query/useAuth.ts
  src/screens/auth/main/index.tsx
  src/screens/home/index.tsx
  src/screens/home/styled.ts
Labels: ✨ 기능

#33 feat: add slider component
  src/assets/images/index.ts
  src/assets/images/keyboard.webp
  src/components/common/GoodsSection/index.tsx
  src/components/common/GoodsSection/styled.ts
  src/components/common/index.ts
  src/components/home/Footer/styled.ts
  src/components/home/Header/styled.ts
  src/components/home/Slider/index.tsx
  src/components/home/Slider/styled.ts
  src/components/home/index.ts
  src/screens/auth/main/index.tsx
  src/screens/auth/main/styled.ts
  src/screens/auth/step1/index.tsx
  src/screens/auth/step1/styled.ts
  src/screens/home/index.tsx
  src/screens/home/styled.ts
Labels: ✨ 기능, 🎨 디자인

#39 feat: add resend disabled
  src/Router.tsx
  src/screens/auth/step2/index.tsx
Labels: ✨ 기능, 🎨 디자인
